### ISSUE TITLE
Convert main code to P-H 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#10] opened 2016-09-26 20:51 UTC

**Comment by savreline** [comment] 2016-09-27 17:24
<img src="https://cloud.githubusercontent.com/assets/21995425/18884507/87d2093e-849c-11e6-8f27-4a19678cc754.png" width=150px>

<img scr="https://cloud.githubusercontent.com/assets/21995425/18884508/87e7d17e-849c-11e6-81e2-713cdf83fb76.png" width=150px> 

So the P-H model works, solution is quite fast and the first plot looks OK.
Yet - steady state is reached way too fast, so need to work on that (i.e. make the solver more aggressive)

**Comment by savreline** [comment] 2016-09-29 17:10
Nice new plots! For 20 time steps and 10 slices. 

![plot_he](https://cloud.githubusercontent.com/assets/21995425/18964248/edc3478a-862c-11e6-9de0-149971e449d0.png)
![plot_n2](https://cloud.githubusercontent.com/assets/21995425/18964247/edbdbc20-862c-11e6-8f8f-279def8eb578.png)

Updated code uploaded, issue_10 branch **restored**.

**Comment by savreline** [comment] 2016-09-30 17:08
Plots for 5 time steps 

<img src="https://cloud.githubusercontent.com/assets/21995425/19000115/b4c325ee-86f5-11e6-9bab-e39400a409d0.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19000120/ba2bfdb2-86f5-11e6-974a-81d0ee70ba29.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19000125/be1ced14-86f5-11e6-8dba-9b9260472118.png" width=250px>

**Comment by savreline** [comment] 2016-09-30 17:25
Plots for 20 time steps 

<img src="https://cloud.githubusercontent.com/assets/21995425/19000561/13e299c2-86f8-11e6-97ee-2cf7eb361865.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19000565/17a5b5e4-86f8-11e6-8067-aa1a5fcfadc9.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19000567/1a53995a-86f8-11e6-902a-549fbb0a747b.png" width=250px>

Still some issues for He, but perhaps because it is so close to N2??? Will check with a lower flux.

**Comment by savreline** [comment] 2016-09-30 18:22
Plots for 20 time steps, with `HX_UA = 3000` (took the heat transfer coefficient lower, to prevent the plots from intersecting each other). Solution time of ~12 min. 

<img src="https://cloud.githubusercontent.com/assets/21995425/19002257/072c25ba-8700-11e6-802b-aa4eb256859d.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19002261/0d20d9ca-8700-11e6-9b8c-614e27ae3689.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19002259/09e7384e-8700-11e6-9db7-89a4dbb36851.png" width=250px>

Still some issues for He, but better

**Comment by nagimov** [comment] 2016-10-01 00:51
@savreline let's look at heat load through iterations (plots which we've discussed today) before closing this one

**Comment by savreline** [comment] 2016-10-03 18:13
@nagimov The heat load looks OK. 

![plot_overall10](https://cloud.githubusercontent.com/assets/21995425/19048258/754f7d60-895a-11e6-8354-2138318ca64c.png)
![plot_q10](https://cloud.githubusercontent.com/assets/21995425/19048257/754d766e-895a-11e6-8693-decf136fa15f.png)

**Comment by nagimov** [comment] 2016-10-03 18:39
@savreline okay this one is just caused by reduced heat load at the end of iteration. Cold stream inlet temp is 100K and with a lower heat load its ability to warm up the cold stream within one slice is lower, so temperature is dropping near the inlet. Closing this issue.
Please submit the latest code as well.

**Closed as completed by nagimov** 2016-10-03 18:39 UTC
Labels: done

**Comment by savreline** [comment] 2016-10-03 20:28
Latest code for this one was submitted
